version: "3.8"

services:
  mysql:
    image: mariadb:11.4
    container_name: zabbix-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-Kv7RJntxue4fyxbz}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zabbix}
      MYSQL_USER: ${MYSQL_USER:-zabbix}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-WWzqJJ3s4SykeDQp}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - zbxnet

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-7.4-latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zabbix}
      MYSQL_USER: ${MYSQL_USER:-zabbix}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-WWzqJJ3s4SykeDQp}
      ZBX_ENABLE_SNMP_TRAPS: "true"
    volumes:
      - ./zbx_env/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zbx_env/externalscripts:/usr/lib/zabbix/externalscripts
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    networks:
      - zbxnet
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 10051 || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 5s

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:alpine-7.4-latest
    container_name: zabbix-frontend
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zabbix}
      MYSQL_USER: ${MYSQL_USER:-zabbix}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-WWzqJJ3s4SykeDQp}
      PHP_TZ: ${TZ:-Europe/Moscow}
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    ports:
      - "3001:3001"
    networks:
      - zbxnet

  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.4-latest
    container_name: zabbix-agent2
    restart: unless-stopped
    privileged: true
    pid: "host"
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: ${ZBX_HOSTNAME:-ubuntu25}
      ZBX_PASSIVE_ALLOW: "true"
      ZBX_ACTIVE_ALLOW: "true"
    volumes:
      - /:/hostfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./zabbix_agent2.conf:/etc/zabbix/zabbix_agent2.conf:ro
    networks:
      - zbxnet
    depends_on:
      zabbix-server:
        condition: service_healthy

  # grafana:
  #   image: grafana/grafana:11.2.0
  #   container_name: grafana
  #   restart: unless-stopped
  #   depends_on:
  #     - zabbix-server
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-aDm1N}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-r4FD6GEH7zsXfXZs}
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./grafana:/var/lib/grafana
  #   networks:
  #     - zbxnet

networks:
  zbxnet:
    driver: bridge
